############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Thrusts"
url = "/thrust"
weight = 2

[[main]]
name = "Team"
url = "/team"
weight = 3

[[main]]
name = "Outreach"
url = "/outreach"
weight = 4

[[main]]
name = "Apply"
url = "/apply/apply"
weight = 5

[[main]]
name= "Seminar"
url = "/seminar"
weight = 6

#[[main]]
#weight = 5
#name = "News"
#url = "/updates"

#[[main]]
#parent = "News"
#name = "Updates"
#url = "/updates"
#
#[[main]]
#parent = "News"
#name = "Publications"
#url = "/pubs"
#
#[[main]]
#parent = "News"
#name = "Alumni"
#url = "/alumni"

#[[main]]
#weight = 6
#name = "Pages"
#
#[[main]]
#parent = "Pages"
#name = "Blog"
#url = "/blog"
#
#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "/contact"
#
#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"
#
#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "/categories"
#
#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "MTSU Quantum Initiative"
url = "https://quantum.mtsu.edu/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
